/** common reducer */
export const SET_SCREEN_LOADER = "SET_SCREEN_LOADER";
export const RESET_INITIAL_STATE_DATA = "RESET_INITIAL_STATE_DATA";

/** auth reducer */
export const SET_USER_CREDENTIALS = "SET_USER_CREDENTIALS";

/** time reducer */
export const SET_USER_TIME_DATA = "SET_USER_TIME_DATA";
export const SET_USERS_TIME_LIST = "SET_USERS_TIME_LIST";
export const SET_USER_WORK_TILL_NOW = "SET_USER_WORK_TILL_NOW";
export const SET_USER_YESTERDAY_AND_TODAY_PUNCH = "SET_USER_YESTERDAY_AND_TODAY_PUNCH";
export const SET_DAY_ID = "SET_DAY_ID";
export const ADD_PUNCH_TIME_DATA = "ADD_PUNCH_TIME_DATA";
export const ADD_EXIT_PUNCH_TIME_DATA = "ADD_EXIT_PUNCH_TIME_DATA";
export const EDIT_PUNCHED_TIME_DATA = "EDIT_PUNCHED_TIME_DATA";
